language: java
jdk: oraclejdk11

branches:
  only:
  - develop
  - master

before_install:
- chmod +x mvnw

deploy:
  provider: cloudfoundry
  username: polushan@yandex.ru
  api: https://api.run.pivotal.io
  organization: PingPong
  space: development
  manifest: manifest.yml
  app_name: pong-service
  on:
    branch: master