eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://pingpong-discovery.herokuapp.com/eureka
    instance:
#      hostname: cloud-pong-service.herokuapp.com
      preferIpAddress: true
      nonSecurePortEnabled: false
      securePortEnabled: false