eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://discovery-cheerful-fox.cfapps.io
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80